server:
  port: ${PORT:8080}
  forward-headers-strategy: framework

spring:
  datasource:
    url: jdbc:h2:file:./data/foodaiddb;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE;DEFAULT_NULL_ORDERING=HIGH;AUTO_RECONNECT=TRUE
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.H2Dialect
    open-in-view: true
    properties:
      hibernate:
        format_sql: true
  thymeleaf:
    cache: false
  flyway:
    enabled: true
    locations: classpath:db/migration
