CREATE TABLE beneficiary (
    id_beneficiary BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category VARCHAR(100) NOT NULL,
    full_name VARCHAR(200) NOT NULL,
    phone VARCHAR(30) NOT NULL,
    address TEXT NOT NULL,
    benefit_status VARCHAR(100),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE ration (
    id_ration BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(150) NOT NULL,
    period VARCHAR(100),
    description TEXT,
    active BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE product (
    id_product BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(150) NOT NULL,
    unit VARCHAR(50) NOT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE volunteer (
    id_volunteer BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name VARCHAR(200) NOT NULL,
    phone VARCHAR(30) NOT NULL,
    transport_type VARCHAR(100),
    availability_status VARCHAR(50) NOT NULL DEFAULT 'Доступен'
);

CREATE TABLE help_request (
    id_request BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_beneficiary BIGINT NOT NULL,
    id_ration BIGINT NOT NULL,
    request_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    delivery_address TEXT NOT NULL,
    status VARCHAR(50) NOT NULL DEFAULT 'NEW',
    intake_channel VARCHAR(100),
    comment TEXT,
    CONSTRAINT fk_request_beneficiary FOREIGN KEY (id_beneficiary)
        REFERENCES beneficiary(id_beneficiary) ON DELETE CASCADE,
    CONSTRAINT fk_request_ration FOREIGN KEY (id_ration)
        REFERENCES ration(id_ration) ON DELETE RESTRICT
);

CREATE TABLE ration_composition (
    id_ration BIGINT NOT NULL,
    id_product BIGINT NOT NULL,
    quantity NUMERIC(10,2) NOT NULL,
    CONSTRAINT pk_ration_composition PRIMARY KEY (id_ration, id_product),
    CONSTRAINT fk_ration_comp_ration FOREIGN KEY (id_ration)
        REFERENCES ration(id_ration) ON DELETE CASCADE,
    CONSTRAINT fk_ration_comp_product FOREIGN KEY (id_product)
        REFERENCES product(id_product) ON DELETE RESTRICT
);

CREATE TABLE delivery (
    id_delivery BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_request BIGINT NOT NULL,
    id_volunteer BIGINT NOT NULL,
    planned_date TIMESTAMP NOT NULL,
    actual_date TIMESTAMP,
    status VARCHAR(50) NOT NULL DEFAULT 'ASSIGNED',
    note TEXT,
    CONSTRAINT fk_delivery_request FOREIGN KEY (id_request)
        REFERENCES help_request(id_request) ON DELETE CASCADE,
    CONSTRAINT fk_delivery_volunteer FOREIGN KEY (id_volunteer)
        REFERENCES volunteer(id_volunteer) ON DELETE RESTRICT,
    CONSTRAINT uq_delivery_request UNIQUE (id_request)
);
